/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.52
 * Generated at: 2021-11-24 02:56:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.Intranet;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class view_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/C:/SpringFrameWork_STS/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Intranet/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/C:/SpringFrameWork_STS/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Intranet/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1637549191945L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005ftype_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005ftype_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005ftype_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<head>\r\n");
      out.write("<script src=\"http://code.jquery.com/jquery-1.11.3.js\"></script>\r\n");
      out.write("<title>게시물 보기</title>\r\n");
      out.write("<style>\r\n");
      out.write("body { font-family: \"나눔고딕\", \"맑은고딕\" }\r\n");
      out.write("h1 { font-family: \"HY견고딕\" }\r\n");
      out.write("\r\n");
      out.write("a:link { color: black; }\r\n");
      out.write("a:visited { color: black; }\r\n");
      out.write("\r\n");
      out.write("a { text-decoration : none; cursor: hand; }\r\n");
      out.write("\r\n");
      out.write("div.left { \r\n");
      out.write("	width: 55%; \r\n");
      out.write("	height: 100%; \r\n");
      out.write("	margin-top: 30px;\r\n");
      out.write("	margin-left:0px;\r\n");
      out.write("	padding-right:0px;	\r\n");
      out.write("	display:inline-block;\r\n");
      out.write("	/* border:3px solid gray; */\r\n");
      out.write("}\r\n");
      out.write("div.right { \r\n");
      out.write("	width: 35%; \r\n");
      out.write("	height: 100%; \r\n");
      out.write("	vertical-align: top;\r\n");
      out.write("	margin-top: 70px;	\r\n");
      out.write("	display:inline-block;\r\n");
      out.write("	/* border:3px solid gray; */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navi_top {	\r\n");
      out.write("	width: 100%;\r\n");
      out.write("    height:auto;\r\n");
      out.write("    position: fixed;\r\n");
      out.write("    top: 0;\r\n");
      out.write("    left:0;\r\n");
      out.write("    right:0;\r\n");
      out.write("	text-align: center; \r\n");
      out.write("	background-color: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navi_top .loginInfo {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	height : 10%\r\n");
      out.write("}\r\n");
      out.write(".navi_top .main_menu {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	height : 90%\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navi_top > a {\r\n");
      out.write("	display:block; \r\n");
      out.write("	text-decoration : none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navi_top > a:link, .navi_top > a:visited, .navi_top > a:active { color: white; }\r\n");
      out.write("\r\n");
      out.write(".navi_top .main_menu > li {\r\n");
      out.write("    float:left;\r\n");
      out.write("    width:19%;\r\n");
      out.write("    height: auto;\r\n");
      out.write("    line-height: 50px;\r\n");
      out.write("    list-style: none;\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("    position: relative;\r\n");
      out.write("    margin: 0px,0px,0px,0px;\r\n");
      out.write("    background-color: #14D3FF; \r\n");
      out.write("        \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navi_top .main_menu > li:hover {\r\n");
      out.write("    background-color: #1E90FF;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navi_top .main_menu .sub_menu { \r\n");
      out.write("    list-style: none; \r\n");
      out.write("    display: none;\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    padding-left: 0;\r\n");
      out.write("    padding-right: 0;\r\n");
      out.write("\r\n");
      out.write("	background-color: #3CAEFF;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navi_top .main_menu>li:hover .sub_menu {\r\n");
      out.write("    display:block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sub_menu a {\r\n");
      out.write("			color: white;\r\n");
      out.write("			padding: 1px;\r\n");
      out.write("			text-decoration: none;\r\n");
      out.write("			display: block;\r\n");
      out.write("}\r\n");
      out.write(".sub_menu a:hover { background-color: #3CFBFF; }\r\n");
      out.write("\r\n");
      out.write(".navi_bottom { text-align: center; margin-top: 20px; }\r\n");
      out.write("\r\n");
      out.write(".navi_bottom > a:link, .navi_bottom > a:visited {\r\n");
      out.write("			background-color: #FFA500;\r\n");
      out.write("			color: maroon;\r\n");
      out.write("			padding: 15px 25px;\r\n");
      out.write("			text-align: center;	\r\n");
      out.write("			display: inline-block;\r\n");
      out.write("}\r\n");
      out.write(".navi_bottom > a:hover, .navi_bottom > a:active { \r\n");
      out.write("	background-color: #1E90FF;\r\n");
      out.write("	text-decoration : none; \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".registerForm {\r\n");
      out.write("  /* position:absolute; */\r\n");
      out.write("  \r\n");
      out.write("  margin-top: 50px;\r\n");
      out.write("  margin-left: 50px;\r\n");
      out.write("  margin-right: 50px;\r\n");
      out.write("  padding-right: 30px;\r\n");
      out.write("  width:80%;\r\n");
      out.write("  height:820px;\r\n");
      out.write("  /* padding: 20px, 20px; */\r\n");
      out.write("  background-color:#FFFFFF;\r\n");
      out.write("  text-align:center;\r\n");
      out.write("\r\n");
      out.write("  border-right:3px solid gray; \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nameForm, .titleForm, .fileListForm {\r\n");
      out.write("  border-bottom: 2px solid #adadad;\r\n");
      out.write("  margin: 20px;\r\n");
      out.write("  padding: 5px 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".writer, .title, .fileList {\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  border:none;\r\n");
      out.write("  outline:none;\r\n");
      out.write("  color: #636e72;\r\n");
      out.write("  font-size:16px;\r\n");
      out.write("  height:25px;\r\n");
      out.write("  background: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".textareaForm {\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  height: 350px;\r\n");
      out.write("  overflow: auto;\r\n");
      out.write("  margin: 22px;\r\n");
      out.write("  padding: 10px;\r\n");
      out.write("  box-sizing: border-box;\r\n");
      out.write("  border: solid #adadad;\r\n");
      out.write("  text-align: left;\r\n");
      out.write("  font-size: 16px;\r\n");
      out.write("  resize: both;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#replyNotice {\r\n");
      out.write("	width: 90%;\r\n");
      out.write("	border: 1px solid skyblue; \r\n");
      out.write("	background-color: #0AC9FF; \r\n");
      out.write("	color: white; \r\n");
      out.write("	padding: 5px;\r\n");
      out.write("	font-size:100%;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("	display:inline-block;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".likeClick, .dislikeClick {\r\n");
      out.write("    padding: 10px 10px;\r\n");
      out.write("	text-align: center;	\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("    border: solid 1px #a0a0a0;\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    background-color: #d2d2d2;\r\n");
      out.write("    border-radius: 20px\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("function confirmCheck(){\r\n");
      out.write("	if(confirm(\"정말 삭제 하시겠습니까?\")==true) location.href='/Intranet/delete?bno=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${bno}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("&num=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${num}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function fileDownload(file_no){\r\n");
      out.write("	\r\n");
      out.write("	location.href='/Intranet/fileDownload?file_no=' + file_no;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function replyRegister() { //form 데이터 전송 --> 반드시 serialize()를 해야 한다.\r\n");
      out.write("	\r\n");
      out.write("	if($(\"#replyContent\").val() == \"\") {alert(\"댓글을 입력하세요.\"); $(\"#replyContent\").focus();return false;}\r\n");
      out.write("	\r\n");
      out.write("	var queryString = $(\"form[name=formReply]\").serialize();\r\n");
      out.write("	$.ajax({\r\n");
      out.write("		url : \"/Intranet/replyInsert?option=I\",\r\n");
      out.write("		type : \"post\",\r\n");
      out.write("		dataType : \"json\",\r\n");
      out.write("		data : queryString,\r\n");
      out.write("		success : replyList,\r\n");
      out.write("		error : function(data) {\r\n");
      out.write("						alert(\"서버오류 문제로 댓글 등록이 실패 했습니다. 잠시 후 다시 시도해주시기 바랍니다.\");\r\n");
      out.write("              	    	return false;\r\n");
      out.write("				}\r\n");
      out.write("	}); //End od ajax\r\n");
      out.write("	$(\"#replyContent\").val(\"\");	\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function pageStart() {\r\n");
      out.write("	\r\n");
      out.write("	var queryString = { \"bno\": ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${bno}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" };\r\n");
      out.write("	$.ajax({\r\n");
      out.write("		url : \"/Intranet/replyInsert?option=L\",\r\n");
      out.write("		type : \"post\",\r\n");
      out.write("		dataType : \"json\",\r\n");
      out.write("		data : queryString,\r\n");
      out.write("		success : replyList,\r\n");
      out.write("		error : function(data) {\r\n");
      out.write("						alert(\"서버오류 문제로 댓글 등록이 실패 했습니다. 잠시 후 다시 시도해주시기 바랍니다.\");\r\n");
      out.write("              	    	return false;\r\n");
      out.write("				}\r\n");
      out.write("	}); //End od ajax\r\n");
      out.write("	\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function replyList(list){\r\n");
      out.write("	\r\n");
      out.write("	var result = \"\";\r\n");
      out.write("	$.each(list, function(index,item){		\r\n");
      out.write("		var username = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${username}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("		var authority_code = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${authority_code}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("		\r\n");
      out.write("		<!-- 날짜, 시간 포맷 계산 시작-->\r\n");
      out.write("		date = new Date(item[\"regDate\"]);\r\n");
      out.write("		let month = date.getMonth() + 1;\r\n");
      out.write("        let day = date.getDate();\r\n");
      out.write("        let hour = date.getHours();\r\n");
      out.write("        let minute = date.getMinutes();\r\n");
      out.write("        let second = date.getSeconds();\r\n");
      out.write("\r\n");
      out.write("        month = month >= 10 ? month : '0' + month;\r\n");
      out.write("        day = day >= 10 ? day : '0' + day;\r\n");
      out.write("        hour = hour >= 10 ? hour : '0' + hour;\r\n");
      out.write("        minute = minute >= 10 ? minute : '0' + minute;\r\n");
      out.write("        second = second >= 10 ? second : '0' + second;\r\n");
      out.write("        \r\n");
      out.write("        let regDate = date.getFullYear() + '-' + month + '-' + day + ' ' + hour + ':' + minute + ':' + second;\r\n");
      out.write("        <!-- 날짜, 시간 포맷 계산 종료-->\r\n");
      out.write("        \r\n");
      out.write("		result += \"<div id='replyListView'>\";\r\n");
      out.write("		<!-- result += \"<div id='replyListView\" + item[\"replyBno\"]  + \"'>\"; -->\r\n");
      out.write("			result += \"<div id = '\" + item[\"replyBno\"] + \"' style='font-size: 0.8em'>\";\r\n");
      out.write("				result += \"작성자 : \" + item[\"writer\"];\r\n");
      out.write("								\r\n");
      out.write("				if(item[\"writer\"] == username || authority_code == '01') {\r\n");
      out.write("					result += \"[<a href=\" + \"'javascript:replyModify(\" + item[\"replyBno\"] + \")' style='cursor:pointer;'>수정</a> | \" ;\r\n");
      out.write("					result += \"<a href=\" + \"'javascript:replyDelete(\" + item[\"replyBno\"] + \")' style='cursor:pointer;'>삭제</a>]\" ;\r\n");
      out.write("				}\r\n");
      out.write("				\r\n");
      out.write("				result += \"&nbsp;&nbsp;\" + regDate\r\n");
      out.write("				result += \"<div style='width:90%; height: auto; border-top: 1px solid gray; overflow: auto;'>\";\r\n");
      out.write("				result += \"<pre class='\" + item[\"replyBno\"] + \"'>\" + item[\"replyContent\"] + \"</pre></div>\";\r\n");
      out.write("			result += \"</div>\";\r\n");
      out.write("		result += \"</div><br>\";\r\n");
      out.write("	})\r\n");
      out.write("	$(\"#replyListView\").remove();\r\n");
      out.write("	$(\"#replyList\").html(result);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function replyDelete(replyBno) { //JSON --> MAP 타입일 경우 contentType를 반드시 입력...\r\n");
      out.write("	if(confirm(\"정말로 삭제하시겠습니까?\") == true) {\r\n");
      out.write("		var queryString = { \"replyBno\": replyBno, \"bno\": ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${bno}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" };\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			url : \"/Intranet/replyDelete\",\r\n");
      out.write("			type : \"post\",\r\n");
      out.write("			dataType : \"json\",\r\n");
      out.write("			contentType: 'application/json; charset=UTF-8',\r\n");
      out.write("			data : JSON.stringify(queryString),\r\n");
      out.write("			success : replyList,\r\n");
      out.write("			error : function(data) {\r\n");
      out.write("							alert(\"서버오류 문제로 댓글 등록이 실패 했습니다. 잠시 후 다시 시도해주시기 바랍니다.\");\r\n");
      out.write("	              	    	return false;\r\n");
      out.write("					}\r\n");
      out.write("		}); //End od ajax\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function replyModify(replyBno) {\r\n");
      out.write("\r\n");
      out.write("	var replyContent = $(\".\" + replyBno).html();\r\n");
      out.write("	\r\n");
      out.write("	var strReplyList = \"<form id='formModify' name='formModify' method='POST'>\"\r\n");
      out.write("					+ \"작성자 : ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${username}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("&nbsp;\"\r\n");
      out.write("					+ \"<input type='button' id='btn_replyModify' value='수정'>\"\r\n");
      out.write("					+ \"<input type='button' id='btn_replyModifyCancel' value='취소'>\"\r\n");
      out.write("					+ \"<input type='hidden' name='replyBno' value='\" + replyBno + \"'>\"\r\n");
      out.write("					+ \"<input type='hidden' name='bno' value='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${bno}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'>\"\r\n");
      out.write("					+ \"<input type='hidden' id='writer' name='writer' value='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${username}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'>\"\r\n");
      out.write("					+ \"<input type='hidden' id='uerid' name='userid' value='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'>\"\r\n");
      out.write("					+ \"<textarea id='replyContent' name='replyContent' cols='80' rows='5' maxlength='150' placeholder='글자수:150자 이내'>\" + replyContent + \"</textarea><br>\"\r\n");
      out.write("					+ \"</form>\";\r\n");
      out.write("	$('#' + replyBno).after(strReplyList);				\r\n");
      out.write("	$('#' + replyBno).remove();\r\n");
      out.write("\r\n");
      out.write("	$(\"#btn_replyModify\").on(\"click\", function(){\r\n");
      out.write("		var queryString = $(\"form[name=formModify]\").serialize();\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			url : \"/Intranet/replyInsert?option=U\",\r\n");
      out.write("			type : \"post\",\r\n");
      out.write("			dataType : \"json\",\r\n");
      out.write("			data : queryString,\r\n");
      out.write("			success : replyList,\r\n");
      out.write("			error : function(data) {\r\n");
      out.write("							alert(\"서버오류 문제로 댓글 등록이 실패 했습니다. 잠시 후 다시 시도해주시기 바랍니다.\");\r\n");
      out.write("	              	    	return false;\r\n");
      out.write("			}\r\n");
      out.write("		}); //End of $.ajax\r\n");
      out.write("	 }); //End of $(\"#btn_replyModify\")\r\n");
      out.write("	\r\n");
      out.write("	 $(\"#btn_replyModifyCancel\").on(\"click\", function(){\r\n");
      out.write("		 if(confirm(\"정말로 취소하시겠습니까?\") == true  ) { $(\"#replyListView\").remove(); pageStart(); }\r\n");
      out.write("	 });	 \r\n");
      out.write("	\r\n");
      out.write("}\r\n");
      out.write("	\r\n");
      out.write("function replyCancel() { \r\n");
      out.write("		if(confirm(\"정말로 취소 하시겠습니까?\") == true) { $(\"#replyContent\").val(\"\"); $(\"#replyContent\").focus(); }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function mbrDelete() {\r\n");
      out.write("	\r\n");
      out.write("	if(confirm(\"사용자 탈퇴를 하시면 작성하셨던 모든 게시물도 함께 삭제됩니다. \\n정말로 사용자 탈퇴 하시겠습니까?\") == true)\r\n");
      out.write("	 	{ alert(\"사용자 정보기 삭제 되었습니다.\"); document.location.href='/Intranet/mbrInfoDelete';  } 	\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("$(document).ready(function() {\r\n");
      out.write("    var likeCnt = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${view.likeCnt}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("; \r\n");
      out.write("    var dislikeCnt = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${view.dislikeCnt}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("; \r\n");
      out.write("    var myLikeCheck = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${myLikeCheck}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'; \r\n");
      out.write("    var myDislikeCheck = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${myDislikeCheck}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'; \r\n");
      out.write("    var username = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${username}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("    $(\"#like\").html(likeCnt);\r\n");
      out.write("    $(\"#dislike\").html(dislikeCnt);\r\n");
      out.write("\r\n");
      out.write("    if(myLikeCheck == \"Y\") $(\".likeClick\").css(\"background-color\", \"#00B9FF\"); \r\n");
      out.write("        else if(myDislikeCheck == \"Y\") $(\".dislikeClick\").css(\"background-color\", \"#00B9FF\"); \r\n");
      out.write("\r\n");
      out.write("    if(myLikeCheck == \"Y\") $(\"#myChoice\").html(username + \"님의 선택은 좋아요입니다.\"); \r\n");
      out.write("            else if(myDislikeCheck == \"Y\") $(\"#myChoice\").html(username + \"님의 선택은 싫어요입니다.\"); \r\n");
      out.write("            else if(myLikeCheck == \"N\" && myDislikeCheck == \"N\") $(\"#myChoice\").html(username + \"님은 아직 선택을 안 했네요\"); \r\n");
      out.write("    \r\n");
      out.write("    $(\"#likeClick\").on(\"click\", function() { \r\n");
      out.write("        \r\n");
      out.write("        if(myLikeCheck == \"Y\" && myDislikeCheck ==\"N\") {\r\n");
      out.write("            alert(\"좋아요를 취소합니다.\"); \r\n");
      out.write("            var checkCnt = 1;  //likeCnt --;\r\n");
      out.write("            myLikeCheck = \"N\";\r\n");
      out.write("            sendDataToServer(myLikeCheck,myDislikeCheck,checkCnt); \r\n");
      out.write("            $(\".likeClick\").css(\"background-color\", \"#d2d2d2\"); \r\n");
      out.write("        }else if(myLikeCheck == \"N\" && myDislikeCheck ==\"Y\") {\r\n");
      out.write("            alert(\"싫어요가 취소되고 좋아요가 등록됩니다.\");\r\n");
      out.write("            var checkCnt = 2; // likeCnt ++ , dislikeCnt --\r\n");
      out.write("            myLikeCheck = \"Y\";\r\n");
      out.write("            myDislikeCheck = \"N\";\r\n");
      out.write("            sendDataToServer(myLikeCheck,myDislikeCheck,checkCnt);  \r\n");
      out.write("            $(\".likeClick\").css(\"background-color\", \"#00B9FF\"); \r\n");
      out.write("            $(\".dislikeClick\").css(\"background-color\", \"#d2d2d2\");\r\n");
      out.write("        } else if(myLikeCheck == \"N\" && myDislikeCheck ==\"N\") {\r\n");
      out.write("            alert(\"좋아요를 선택 했습니다.\")\r\n");
      out.write("        	var checkCnt = 3; //likeCnt ++\r\n");
      out.write("            myLikeCheck = \"Y\";\r\n");
      out.write("            sendDataToServer(myLikeCheck,myDislikeCheck,checkCnt);\r\n");
      out.write("            $(\".likeClick\").css(\"background-color\", \"#00B9FF\"); \r\n");
      out.write("        }\r\n");
      out.write("        if(myLikeCheck == \"Y\") $(\"#myChoice\").html(username + \"님의 선택은 좋아요입니다.\"); \r\n");
      out.write("            else if(myDislikeCheck == \"Y\") $(\"#myChoice\").html(username + \"님의 선택은 싫어요입니다.\"); \r\n");
      out.write("            else if(myLikeCheck == \"N\" && myDislikeCheck == \"N\") $(\"#myChoice\").html(username + \"님은 아직 선택을 안 했네요\"); \r\n");
      out.write("    })\r\n");
      out.write("    $(\"#disLikeClick\").on(\"click\", function() {\r\n");
      out.write("        \r\n");
      out.write("        if(myDislikeCheck == \"Y\" && myLikeCheck ==\"N\") {\r\n");
      out.write("            alert(\"싫어요를 취소합니다.\"); \r\n");
      out.write("            var checkCnt = 4; // dislikeCnt --\r\n");
      out.write("            myDislikeCheck = \"N\";\r\n");
      out.write("            sendDataToServer(myLikeCheck,myDislikeCheck,checkCnt);\r\n");
      out.write("            $(\".dislikeClick\").css(\"background-color\", \"#d2d2d2\"); \r\n");
      out.write("        } else if(myDislikeCheck = \"N\" && myLikeCheck ==\"Y\") {\r\n");
      out.write("            alert(\"좋아요가 취소되고 싫어요가 등록됩니다.\");\r\n");
      out.write("            var checkCnt = 5; //likeCnt -- , dislikeCnt ++            \r\n");
      out.write("            myLikeCheck = \"N\";            \r\n");
      out.write("            myDislikeCheck = \"Y\";\r\n");
      out.write("            sendDataToServer(myLikeCheck,myDislikeCheck,checkCnt);\r\n");
      out.write("            $(\".likeClick\").css(\"background-color\", \"#d2d2d2\"); \r\n");
      out.write("            $(\".dislikeClick\").css(\"background-color\", \"#00B9FF\"); \r\n");
      out.write("        } else if(myDislikeCheck = \"N\" && myLikeCheck ==\"N\") {\r\n");
      out.write("            alert(\"싫어요를 선택했습니다.\");\r\n");
      out.write("        	var checkCnt = 6; //dislikeCnt ++\r\n");
      out.write("            myDislikeCheck = \"Y\";\r\n");
      out.write("            sendDataToServer(myLikeCheck,myDislikeCheck,checkCnt);\r\n");
      out.write("            $(\".dislikeClick\").css(\"background-color\", \"#00B9FF\"); \r\n");
      out.write("        }\r\n");
      out.write("        if(myLikeCheck == \"Y\") $(\"#myChoice\").html(username + \"님의 선택은 좋아요입니다.\"); \r\n");
      out.write("            else if(myDislikeCheck == \"Y\") $(\"#myChoice\").html(username + \"님의 선택은 싫어요입니다.\"); \r\n");
      out.write("            else if(myLikeCheck == \"N\" && myDislikeCheck == \"N\") $(\"#myChoice\").html(username + \"님은 아직 선택을 안 했네요\"); \r\n");
      out.write("    })\r\n");
      out.write("\r\n");
      out.write("})\r\n");
      out.write("\r\n");
      out.write("function sendDataToServer(myLike, myDislike, checkCount) {\r\n");
      out.write("\r\n");
      out.write("    var myLikeCheck = myLike;\r\n");
      out.write("    var myDislikeCheck = myDislike;\r\n");
      out.write("    var checkCnt = checkCount;\r\n");
      out.write("    var bno = 45;\r\n");
      out.write("\r\n");
      out.write("    var queryString = { \"bno\":");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${view.bno}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(", \"userid\": \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\", \"myLikeCheck\": myLikeCheck, \"myDislikeCheck\": myDislikeCheck, \"checkCnt\": checkCnt };\r\n");
      out.write("    $.ajax({ //JSON --> MAP 타입일 경우 contentType를 반드시 입력...\r\n");
      out.write("        url: '/Intranet/likeCheck',\r\n");
      out.write("        method: 'POST',\r\n");
      out.write("        data: JSON.stringify(queryString),\r\n");
      out.write("        contentType: 'application/json; charset=UTF-8',\r\n");
      out.write("        dataType : 'json',\r\n");
      out.write("        success: function(map) {\r\n");
      out.write("            $(\"#like\").html(map[\"likeCnt\"]);\r\n");
      out.write("            $(\"#dislike\").html(map[\"dislikeCnt\"]);\r\n");
      out.write("        },\r\n");
      out.write("        error: function(map) {\r\n");
      out.write("			alert(\"서버오류 문제로 좋아요/싫어요 등록이 실패 했습니다. 잠시 후 다시 시도해주시기 바랍니다.\");\r\n");
      out.write("  	    	return false;\r\n");
      out.write("	}\r\n");
      out.write("    }); //End of ajax\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body onload=\"pageStart()\"> \r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/Intranet/view.jsp(451,0) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userid == null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("<script>\r\n");
          out.write("	document.location.href='/';\r\n");
          out.write("</script>\r\n");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/Intranet/view.jsp(457,0) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userid != null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\r\n");
          out.write("<div class=\"navi_top\">\r\n");
          out.write(" <div class=\"loginInfo\" style=\"text-align: right; vertival-align: middle\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${username}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write('님');
          out.write('(');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${authority_code}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(")이 로그인 하셨습니다.</div>\r\n");
          out.write(" <ul class=\"main_menu\">\r\n");
          out.write(" 	       <li><a href=\"#\">사용자 정보</a>\r\n");
          out.write("                <ul class=\"sub_menu\">\r\n");
          out.write("                    <li><a href=\"/Intranet/mbrInfoView\"\">정보 조회</a></li>\r\n");
          out.write("                    <li><a href=\"/Intranet/logout\">로그아웃</a></li>\r\n");
          out.write("                    <li><a href=\"javascript:mbrDelete()\">회원탈퇴</a></li>\r\n");
          out.write("                </ul>    \r\n");
          out.write("            </li>\r\n");
          out.write("            <li><a href=\"#\">게시판</a>\r\n");
          out.write("                <ul class=\"sub_menu\">\r\n");
          out.write("                    <li><a href=\"/Intranet/listPage?num=1\">목록 보기</a></li>\r\n");
          out.write("                    <li><a href=\"/Intranet/write?num=1\">게시글 등록</a></li>\r\n");
          out.write("                </ul>\r\n");
          out.write("            </li>\r\n");
          out.write("            <li><a href=\"#\">일정 관리</a>\r\n");
          out.write("               <ul class=\"sub_menu\">\r\n");
          out.write("                    <li><a href=\"/Intranet/calendarView\">일정보기</a></li>\r\n");
          out.write("               </ul>\r\n");
          out.write("            </li>            \r\n");
          out.write("            <li><a href=\"/Intranet/eduView\">강의</a>\r\n");
          out.write("            </li>\r\n");
          out.write("            <li><a href=\"/Intranet/sourceView\">소스 보기</a>\r\n");
          out.write("            </li>\r\n");
          out.write("</ul>\r\n");
          out.write("</div>\r\n");
          out.write("\r\n");
          out.write("<div class=\"left\">\r\n");
          out.write("<form name=\"registerForm\" method=\"post\" class=\"registerForm\">\r\n");
          out.write("\r\n");
          out.write("         <h1>제목 : ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${view.title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</h1>\r\n");
          out.write("         <div class=\"nameForm\">\r\n");
          out.write("         	<input type=\"hidden\" name=\"userid\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">\r\n");
          out.write("         	<input type=\"hidden\" name=\"searchType\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${searchType}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">\r\n");
          out.write("         	<input type=\"hidden\" name=\"keyword\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${keyword}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">\r\n");
          out.write("         	<p style=\"text-align:left;\">작성자 : ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${view.writer}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("님</p>\r\n");
          out.write("         </div>\r\n");
          out.write("         <div class=\"titleForm\"><p style=\"text-align:left;\">작성일자 : ");
          if (_jspx_meth_fmt_005fformatDate_005f0(_jspx_th_c_005fif_005f1, _jspx_page_context))
            return true;
          out.write("</p></div>\r\n");
          out.write("         <div class=\"textareaForm\" ><pre>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${view.content}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</pre></div>\r\n");
          out.write("         <div class=\"likeForm\">\r\n");
          out.write("         	<span id='like'></span>&nbsp;<a href='#' id=\"likeClick\" class=\"likeClick\">좋아요</a>\r\n");
          out.write("        	<a href=\"#\" id=\"disLikeClick\" class=\"dislikeClick\">싫어요</a>&nbsp;<span id=\"dislike\"></span><br>\r\n");
          out.write("  			<span id='myChoice' style='color:red'></span>\r\n");
          out.write("         </div>\r\n");
          out.write("         ");
          if (_jspx_meth_c_005fif_005f2(_jspx_th_c_005fif_005f1, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("</form>\r\n");
          out.write("</div> <!-- left End  -->	\r\n");
          out.write("\r\n");
          out.write("<div class=\"right\">\r\n");
          out.write("\r\n");
          out.write("	<p id=\"replyNotice\">댓글을 작성해 주세요</p>\r\n");
          out.write("	<div id='formDiv' style=\"width:100%; height: auto; overflow:auto; font-size: 0.8em\">\r\n");
          out.write("		<form id=\"formReply\" name=\"formReply\" method=\"POST\"> \r\n");
          out.write("		작성자 : ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${username}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("&nbsp;<input type='button' id='btn_replyRegister' value='등록' onclick='replyRegister()'>\r\n");
          out.write("			<input type='button' id='btn_replyCancel' value='취소' onclick='replyCancel()'>\r\n");
          out.write("			<input type='hidden' name='bno' value='");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${bno}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("'>\r\n");
          out.write("			<input type='hidden' name='userid' value='");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("'>\r\n");
          out.write("			<input type='hidden' id='writer' name='writer' value='");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${username}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("'>\r\n");
          out.write("			<textarea id='replyContent' name='replyContent' cols='80' rows='5' maxlength='150' placeholder='글자수:150자 이내'></textarea><br>\r\n");
          out.write("		</form>\r\n");
          out.write("	</div>\r\n");
          out.write("	<hr>\r\n");
          out.write("	\r\n");
          out.write("	<div id=\"replyList\" style=\"width:100%; height:600px; overflow:auto;\">\r\n");
          out.write("		<div id=\"replyListView\"></div> \r\n");
          out.write("	</div><!-- replyList End  -->		\r\n");
          out.write("</div>\r\n");
          out.write("	\r\n");
          out.write("<div class=\"navi_bottom\">\r\n");
          out.write("				");
          if (_jspx_meth_c_005fif_005f3(_jspx_th_c_005fif_005f1, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("					\r\n");
          out.write("				<a href=\"/Intranet/listPage?num=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${num}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("&searchType=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${searchType}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("&keyword=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${keyword}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" onMouseover=\"this.style.textDecoration='underline';\" \r\n");
          out.write("						onmouseout=\"this.style.textDecoration='none';\">목록보기</a> &nbsp;&nbsp;\r\n");
          out.write("\r\n");
          out.write("				");
          if (_jspx_meth_c_005fif_005f4(_jspx_th_c_005fif_005f1, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\r\n");
          out.write("				<a href=\"/Intranet/write?num=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${num}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" onMouseover=\"this.style.textDecoration='underline';\" \r\n");
          out.write("						onmouseout=\"this.style.textDecoration='none';\">글 작성</a> &nbsp;&nbsp;\r\n");
          out.write("\r\n");
          out.write("				");
          if (_jspx_meth_c_005fif_005f5(_jspx_th_c_005fif_005f1, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\r\n");
          out.write("</div>\r\n");
          out.write("\r\n");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatDate_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatDate
    org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag _jspx_th_fmt_005fformatDate_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag) _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005ftype_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag.class);
    boolean _jspx_th_fmt_005fformatDate_005f0_reused = false;
    try {
      _jspx_th_fmt_005fformatDate_005f0.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatDate_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
      // /WEB-INF/views/Intranet/view.jsp(497,67) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatDate_005f0.setValue((java.util.Date) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${view.regDate}", java.util.Date.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /WEB-INF/views/Intranet/view.jsp(497,67) name = type type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatDate_005f0.setType("both");
      int _jspx_eval_fmt_005fformatDate_005f0 = _jspx_th_fmt_005fformatDate_005f0.doStartTag();
      if (_jspx_th_fmt_005fformatDate_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005ftype_005fnobody.reuse(_jspx_th_fmt_005fformatDate_005f0);
      _jspx_th_fmt_005fformatDate_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatDate_005f0, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatDate_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
      // /WEB-INF/views/Intranet/view.jsp(504,9) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${file == true}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("         	<div class=\"fileListForm\"><p style=\"text-align:left;\">파일 목록</p></div>\r\n");
          out.write("         	<div class=\"fileList\">	\r\n");
          out.write("         		<p style=\"text-align:left;\">\r\n");
          out.write("        	 		");
          if (_jspx_meth_c_005fforEach_005f0(_jspx_th_c_005fif_005f2, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("         		</p>\r\n");
          out.write("         	</div>       \r\n");
          out.write("         ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f2, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f2);
      // /WEB-INF/views/Intranet/view.jsp(508,12) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/Intranet/view.jsp(508,12) '${fileList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${fileList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/views/Intranet/view.jsp(508,12) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("file");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("         				&nbsp&nbsp&nbsp&nbsp■ <a href=\"javascript:fileDownload(");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${file.file_no}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(')');
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${file.org_file_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</a>&nbsp(");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${file.file_size}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(" kb)<br>\r\n");
            out.write("	         		");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f3_reused = false;
    try {
      _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
      // /WEB-INF/views/Intranet/view.jsp(538,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${viewPrev != 0 }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
      if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("					&nbsp;&nbsp;<a href=\"/Intranet/view?bno=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${viewPrev}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("&num=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${num}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("&searchType=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${searchType}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("&keyword=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${keyword}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" onMouseover=\"this.style.textDecoration='underline';\" \r\n");
          out.write("						onmouseout=\"this.style.textDecoration='none';\">이전글 ▼</a> &nbsp;&nbsp;\r\n");
          out.write("				");
          int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
      _jspx_th_c_005fif_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f4(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f4 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f4_reused = false;
    try {
      _jspx_th_c_005fif_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
      // /WEB-INF/views/Intranet/view.jsp(546,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f4.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${viewNext != 0 }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f4 = _jspx_th_c_005fif_005f4.doStartTag();
      if (_jspx_eval_c_005fif_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("				<a href=\"/Intranet/view?bno=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${viewNext}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("&num=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${num}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("&searchType=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${searchType}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("&keyword=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${keyword}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" onMouseover=\"this.style.textDecoration='underline';\" \r\n");
          out.write("						onmouseout=\"this.style.textDecoration='none';\">다음글 ▲</a> &nbsp;&nbsp;\r\n");
          out.write("				");
          int evalDoAfterBody = _jspx_th_c_005fif_005f4.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f4);
      _jspx_th_c_005fif_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f4, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f5(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f5 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f5_reused = false;
    try {
      _jspx_th_c_005fif_005f5.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f5.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
      // /WEB-INF/views/Intranet/view.jsp(554,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f5.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${msg == true}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f5 = _jspx_th_c_005fif_005f5.doStartTag();
      if (_jspx_eval_c_005fif_005f5 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("				<a href=\"/Intranet/modify?bno=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${view.bno}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("&num=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${num}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("&searchType=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${searchType}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("&keyword=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${keyword}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" onMouseover=\"this.style.textDecoration='underline';\" \r\n");
          out.write("						onmouseout=\"this.style.textDecoration='none';\">글 수정</a> &nbsp;&nbsp;\r\n");
          out.write("					\r\n");
          out.write("				<a href=\"javascript:confirmCheck()\" onMouseover=\"this.style.textDecoration='underline';\" \r\n");
          out.write("						onmouseout=\"this.style.textDecoration='none';\">글 삭제</a> &nbsp;&nbsp;\r\n");
          out.write("				");
          int evalDoAfterBody = _jspx_th_c_005fif_005f5.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f5);
      _jspx_th_c_005fif_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f5, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f5_reused);
    }
    return false;
  }
}
