/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.52
 * Generated at: 2021-11-24 00:12:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.Intranet;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class write_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/C:/SpringFrameWork_STS/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Intranet/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1637549191945L));
    _jspx_dependants.put("/WEB-INF/views/Intranet/../include/nav_top.jsp", Long.valueOf(1637712356077L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>게시물 작성</title>\r\n");
      out.write("<script src=\"//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"http://code.jquery.com/jquery-1.11.3.js\"></script>\r\n");
      out.write("<style>\r\n");
      out.write("body { font-family: \"나눔고딕\", \"맑은고딕\" }\r\n");
      out.write("h1 { font-family: \"HY견고딕\" }\r\n");
      out.write("\r\n");
      out.write(".navi_top { width: 900px; text-align: right; }\r\n");
      out.write(".navi_bottom { text-align: center; }\r\n");
      out.write("\r\n");
      out.write(".registerForm {\r\n");
      out.write("  /* position:absolute; */\r\n");
      out.write("  width:900px;\r\n");
      out.write("  height:auto;\r\n");
      out.write("  padding: 10px, 10px;\r\n");
      out.write("  background-color:#FFFFFF;\r\n");
      out.write("  text-align:center;\r\n");
      out.write("  /* top:50%; \r\n");
      out.write("  left:50%;\r\n");
      out.write("  transform: translate(-50%,-50%);\r\n");
      out.write("  */\r\n");
      out.write("  border:6px solid gray;\r\n");
      out.write("  border-radius: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nameForm, .titleForm, .fileListForm {\r\n");
      out.write("  border-bottom: 2px solid #adadad;\r\n");
      out.write("  margin: 20px;\r\n");
      out.write("  padding: 10px 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".fileuploadForm {\r\n");
      out.write(" margin: 30px;\r\n");
      out.write(" padding: 10px 10px;\r\n");
      out.write(" text-align: left;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".username, .title {\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  border:none;\r\n");
      out.write("  outline:none;\r\n");
      out.write("  color: #636e72;\r\n");
      out.write("  font-size:16px;\r\n");
      out.write("  height:25px;\r\n");
      out.write("  background: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("textarea {\r\n");
      out.write("  width: 850px;\r\n");
      out.write("  height: 300px;\r\n");
      out.write("  padding: 10px;\r\n");
      out.write("  box-sizing: border-box;\r\n");
      out.write("  border: solid #adadad;\r\n");
      out.write("  \r\n");
      out.write("  font-size: 16px;\r\n");
      out.write("  resize: both;\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("#fileClick {\r\n");
      out.write("  border: solid #adadad;\r\n");
      out.write("  background-color: #a0a0a0;\r\n");
      out.write("  width: 900px;\r\n");
      out.write("  height:80px;\r\n");
      out.write("  color: white;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  vertical-align: middle;\r\n");
      out.write("  padding: 10px;\r\n");
      out.write("  font-size:120%;\r\n");
      out.write("  display: table-cell;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".statusbar{\r\n");
      out.write("  border-bottom:1px solid #92AAB0;;\r\n");
      out.write("  min-height:25px;\r\n");
      out.write("  width:99%;\r\n");
      out.write("  padding:10px 10px 0px 10px;\r\n");
      out.write("  vertical-align:top;\r\n");
      out.write("}\r\n");
      out.write(".statusbar:nth-child(odd){\r\n");
      out.write("  background:#EBEFF0;\r\n");
      out.write("}\r\n");
      out.write(".filename{\r\n");
      out.write("  display:inline-block;\r\n");
      out.write("  vertical-align:top;\r\n");
      out.write("  width:250px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".filesize{\r\n");
      out.write("  display:inline-block;\r\n");
      out.write("  vertical-align:top;\r\n");
      out.write("  color:#30693D;\r\n");
      out.write("  width:100px;\r\n");
      out.write("  margin-left:10px;\r\n");
      out.write("  margin-right:5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".progressBar {\r\n");
      out.write("  width: 200px;\r\n");
      out.write("  height: 22px;\r\n");
      out.write("  border: 1px solid #ddd;\r\n");
      out.write("  border-radius: 5px; \r\n");
      out.write("  overflow: hidden;\r\n");
      out.write("  display:inline-block;\r\n");
      out.write("  margin:0px 10px 5px 5px;\r\n");
      out.write("  vertical-align:top;\r\n");
      out.write("  }\r\n");
      out.write("             \r\n");
      out.write(".progressBar div {\r\n");
      out.write("  height: 100%;\r\n");
      out.write("  color: #fff;\r\n");
      out.write("  text-align: right;\r\n");
      out.write("  line-height: 22px; /* same as #progressBar height if we want text middle aligned */\r\n");
      out.write("  width: 0;\r\n");
      out.write("  background-color: #0ba1b5; border-radius: 3px; \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn_delete{\r\n");
      out.write("  background-color:#A8352F;\r\n");
      out.write("  -moz-border-radius:4px;\r\n");
      out.write("  -webkit-border-radius:4px;\r\n");
      out.write("  border-radius:4px;display:inline-block;\r\n");
      out.write("  color:#fff;\r\n");
      out.write("  font-family:arial;font-size:13px;font-weight:normal;\r\n");
      out.write("  padding:4px 15px;\r\n");
      out.write("  cursor:pointer;\r\n");
      out.write("  vertical-align:top\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".register_btn {\r\n");
      out.write("  position:relative;\r\n");
      out.write("  left:20%;\r\n");
      out.write("  transform: translateX(-50%);\r\n");
      out.write("  margin-top: 10px;\r\n");
      out.write("  margin-bottom: 10px;\r\n");
      out.write("  width:40%;\r\n");
      out.write("  height:40px;\r\n");
      out.write("  background: red;\r\n");
      out.write("  background-position: left;\r\n");
      out.write("  background-size: 200%;\r\n");
      out.write("  color:white;\r\n");
      out.write("  font-weight: bold;\r\n");
      out.write("  border:none;\r\n");
      out.write("  cursor:pointer;\r\n");
      out.write("  transition: 0.4s;\r\n");
      out.write("  display:inline;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".cancel_btn  {\r\n");
      out.write("  position:relative;\r\n");
      out.write("  left:20%;\r\n");
      out.write("  transform: translateX(-50%);\r\n");
      out.write("  margin-top: 10px;\r\n");
      out.write("  margin-bottom: 10px;\r\n");
      out.write("  width:40%;\r\n");
      out.write("  height:40px;\r\n");
      out.write("  background: pink;\r\n");
      out.write("  background-position: left;\r\n");
      out.write("  background-size: 200%;\r\n");
      out.write("  color:white;\r\n");
      out.write("  font-weight: bold;\r\n");
      out.write("  border:none;\r\n");
      out.write("  cursor:pointer;\r\n");
      out.write("  transition: 0.4s;\r\n");
      out.write("  display:inline;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("function register(){\r\n");
      out.write("	\r\n");
      out.write("	if($(\"#title\").val() == \"\") { alert(\"제목을 입력하세요.\"); $(\"#title\").focus();  return false; }\r\n");
      out.write("	if($(\"#content\").val() == '') { alert(\"내용을 입력하세요.\"); $(\"#content\").focus(); return false; }\r\n");
      out.write("	\r\n");
      out.write("	if(content_files.length != 0) sendFileToServer();\r\n");
      out.write("	\r\n");
      out.write("	$(\"#registerForm\").attr(\"action\", \"/Intranet/write\").submit();\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("$(document).ready(function(){ \r\n");
      out.write("	var objDragAndDrop = $(\"#fileClick\");\r\n");
      out.write("	//input type=file에 onchange 발생 이벤트\r\n");
      out.write("	$(\"#input_file\").on(\"change\", function(e) {\r\n");
      out.write("		var files = e.originalEvent.target.files;\r\n");
      out.write("    	fileCheck(files);\r\n");
      out.write("	});\r\n");
      out.write("\r\n");
      out.write("	//fileClick 영역 클릭 시 이벤트\r\n");
      out.write("	objDragAndDrop.on('click',function (e){\r\n");
      out.write("        $('#input_file').trigger('click');\r\n");
      out.write("    });\r\n");
      out.write("	\r\n");
      out.write("	$(document).on(\"dragenter\",\"#fileClick\",function(e){\r\n");
      out.write("    	e.stopPropagation(); \r\n");
      out.write("    	e.preventDefault();\r\n");
      out.write("    	$(this).css('border', '2px solid #0B85A1');\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("	$(document).on(\"dragover\",\"#fileClick\",function(e){\r\n");
      out.write("    	e.stopPropagation();\r\n");
      out.write("    	e.preventDefault();\r\n");
      out.write("	});\r\n");
      out.write("	//fileClick 영역에 파일 Drop시 이벤트\r\n");
      out.write("	$(document).on(\"drop\",\"#fileClick\",function(e){\r\n");
      out.write("        e.preventDefault();\r\n");
      out.write("    	var files = e.originalEvent.dataTransfer.files;\r\n");
      out.write("	    fileCheck(files);\r\n");
      out.write("	});\r\n");
      out.write("\r\n");
      out.write("	$(document).on('dragenter', function (e){\r\n");
      out.write("    	e.stopPropagation();\r\n");
      out.write("    	e.preventDefault();\r\n");
      out.write("	});\r\n");
      out.write("\r\n");
      out.write("	$(document).on('dragover', function (e){\r\n");
      out.write("  		e.stopPropagation();\r\n");
      out.write("  		e.preventDefault();\r\n");
      out.write("  		objDragAndDrop.css('border', '2px dotted #0B85A1');\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("	$(document).on('drop', function (e){\r\n");
      out.write("    	e.stopPropagation();\r\n");
      out.write("    	e.preventDefault();\r\n");
      out.write("	});\r\n");
      out.write("\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("var uploadCountLimit = 5; // 업로드 가능한 파일 갯수\r\n");
      out.write("var fileCount = 0; // 파일 현재 필드 숫자 totalCount랑 비교값\r\n");
      out.write("var fileNum = 0; // 파일 고유넘버\r\n");
      out.write("var content_files = new Array(); // 첨부파일 배열\r\n");
      out.write("var rowCount=0;\r\n");
      out.write("\r\n");
      out.write("function fileCheck(files) {\r\n");
      out.write("\r\n");
      out.write("	//var files = e.target.files;\r\n");
      out.write("	var filesArr = Array.prototype.slice.call(files);\r\n");
      out.write("	\r\n");
      out.write("    // 파일 개수 확인 및 제한\r\n");
      out.write("    if (fileCount + filesArr.length > uploadCountLimit) {\r\n");
      out.write("      	alert('파일은 최대 '+uploadCountLimit+'개까지 업로드 할 수 있습니다.');\r\n");
      out.write("      	return;\r\n");
      out.write("    } else {\r\n");
      out.write("    	 fileCount = fileCount + filesArr.length;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    var i =0;\r\n");
      out.write("	filesArr.forEach(function (f) {\r\n");
      out.write("	      var reader = new FileReader();\r\n");
      out.write("	      reader.onload = function (e) {\r\n");
      out.write("	        content_files.push(f);\r\n");
      out.write("			\r\n");
      out.write("	        if(filesArr[i].size > 1073741824) { alert('파일 사이즈는 1GB를 초과할수 없습니다.'); return; }\r\n");
      out.write("		\r\n");
      out.write("	    	rowCount++;\r\n");
      out.write("	        var row=\"odd\";\r\n");
      out.write("	        if(rowCount %2 ==0) row =\"even\";\r\n");
      out.write("	        var statusbar = $(\"<div class='statusbar \"+row+\"' id='file\" + fileNum +\"'></div>\");\r\n");
      out.write("	        var filename = $(\"<div class='filename'>\" + filesArr[i].name + \"</div>\").appendTo(statusbar);\r\n");
      out.write("	        \r\n");
      out.write("	        var sizeStr=\"\";\r\n");
      out.write("	        var sizeKB = filesArr[i].size/1024;\r\n");
      out.write("	        if(parseInt(sizeKB) > 1024){\r\n");
      out.write("	        	var sizeMB = sizeKB/1024;\r\n");
      out.write("	            sizeStr = sizeMB.toFixed(2)+\" MB\";\r\n");
      out.write("	        }else sizeStr = sizeKB.toFixed(2)+\" KB\";	        \r\n");
      out.write("	        \r\n");
      out.write("	        var size = $(\"<div class='filesize'>\" + sizeStr + \"</div>\").appendTo(statusbar);\r\n");
      out.write("	        var progressBar = $(\"<div class='progressBar'><div></div></div>\").appendTo(statusbar);\r\n");
      out.write("	        var btn_delete = $(\"<div class='btn_delete' onclick=fileDelete('file\" + fileNum + \"')>삭제</div></div>\").appendTo(statusbar);\r\n");
      out.write("	       \r\n");
      out.write("			$(\"#fileClick\").after(statusbar); \r\n");
      out.write("			\r\n");
      out.write("	        fileNum ++;\r\n");
      out.write("       \r\n");
      out.write("	        console.log(filesArr[i]);\r\n");
      out.write("	        i++;  \r\n");
      out.write("	      \r\n");
      out.write("	      };\r\n");
      out.write("	      reader.readAsDataURL(f);\r\n");
      out.write("    });\r\n");
      out.write("	\r\n");
      out.write("	$(\"#input_file\").val(\"\");	\r\n");
      out.write("\r\n");
      out.write("}	\r\n");
      out.write("\r\n");
      out.write("function fileDelete(fileNum){\r\n");
      out.write("    var no = fileNum.replace(/[^0-9]/g, \"\");\r\n");
      out.write("    content_files[no].is_delete = true;\r\n");
      out.write("	$('#' + fileNum).remove();\r\n");
      out.write("	fileCount --;\r\n");
      out.write("}  \r\n");
      out.write("\r\n");
      out.write("var progressBarWidth = 200;\r\n");
      out.write("\r\n");
      out.write("function setProgress(progress){       \r\n");
      out.write("    //var ActiveprogressBarWidth =progress*progressBarWidth/ 100;  \r\n");
      out.write("    $(\".progressBar div\").animate({ width: progress }, 10).html(progress + \"% \");\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function sendFileToServer()\r\n");
      out.write("{\r\n");
      out.write("	var form = $(\"#formdata\")[0];\r\n");
      out.write(" 	var formData = new FormData(form);\r\n");
      out.write("	for (var x = 0; x < content_files.length; x++) {\r\n");
      out.write("			if(!content_files[x].is_delete) { \r\n");
      out.write("						\r\n");
      out.write("				formData.append(\"SendToFileList\", content_files[x]);\r\n");
      out.write("			}\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	var uploadURL = \"/Intranet/fileUpload?kinds=R\"; \r\n");
      out.write("     \r\n");
      out.write("	$.ajax({\r\n");
      out.write("        url: uploadURL,\r\n");
      out.write("        type: \"POST\",\r\n");
      out.write("        contentType:false,\r\n");
      out.write("        processData: false,\r\n");
      out.write("        cache: false,\r\n");
      out.write("        enctype: \"multipart/form-data\",\r\n");
      out.write("        data: formData,\r\n");
      out.write("        xhr:function(){\r\n");
      out.write("        	var xhr = $.ajaxSettings.xhr();\r\n");
      out.write("        	xhr.upload.onprogress = function(e){\r\n");
      out.write("        		var per = e.loaded * 100/e.total;\r\n");
      out.write("        		setProgress(per);\r\n");
      out.write("        	};\r\n");
      out.write("        	return xhr;        	\r\n");
      out.write("        },\r\n");
      out.write("        success: function(data){\r\n");
      out.write("        	if(JSON.parse(data)['result'] == \"OK\"){\r\n");
      out.write("        		setProgress(100);\r\n");
      out.write("   	    		alert(\"파일업로드 성공\");\r\n");
      out.write("			} else if(JSON.parse(data)['result'] == \"GOOD\") { }\r\n");
      out.write("			else alert(\"조금 늦네요.잠시만 기다려 주세요.\");\r\n");
      out.write("        },\r\n");
      out.write("        error: function (xhr, status, error) {\r\n");
      out.write("       	    	alert(\"서버오류 문제로 파일 업로드가 안됩니다. 잠시 후 다시 시도해주시기 바랍니다.\");\r\n");
      out.write("       	     return false;\r\n");
      out.write("       	}   \r\n");
      out.write("       \r\n");
      out.write("    }); \r\n");
      out.write("	   	    \r\n");
      out.write(" }\r\n");
      out.write("	\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/Intranet/write.jsp(364,0) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userid == null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("<script>\r\n");
          out.write("	document.location.href='/';\r\n");
          out.write("</script>\r\n");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/Intranet/write.jsp(370,0) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userid != null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("<div class=\"panel-body\" align=\"center\">\r\n");
          out.write("\r\n");
          out.write("<div class=\"navi_top\">\r\n");
          out.write("\r\n");
          out.write("\r\n");
          out.write("<ul> \r\n");
          out.write("\r\n");
          out.write("<span style=\"color:blue; font-weight:bold;\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${username}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write('님');
          out.write('(');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${authority_code}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(")</span>이 로그인 하셨습니다. \r\n");
          out.write("\r\n");
          out.write("[");
          if (_jspx_meth_c_005fif_005f2(_jspx_th_c_005fif_005f1, _jspx_page_context))
            return true;
          out.write('\r');
          out.write('\n');
          if (_jspx_meth_c_005fif_005f3(_jspx_th_c_005fif_005f1, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("<a id=\"hypertext\" href=\"/Intranet/listPage?num=1\" onMouseover=\"this.style.background='pink'; this.style.textDecoration='underline';\" \r\n");
          out.write("onmouseout=\"this.style.background='white'; this.style.textDecoration='none';\">게시판</a> &nbsp;&nbsp; | &nbsp;&nbsp;\r\n");
          out.write("\r\n");
          out.write("<a id=\"hypertext\" href=\"/Intranet/eduView\" onMouseover=\"this.style.background='pink'; this.style.textDecoration='underline';\" \r\n");
          out.write("onmouseout=\"this.style.background='white'; this.style.textDecoration='none';\">강의</a> &nbsp;&nbsp; | &nbsp;&nbsp;\r\n");
          out.write("\r\n");
          out.write("<a id=\"hypertext\" href=\"/Intranet/sourceView\" onMouseover=\"this.style.background='pink'; this.style.textDecoration='underline';\" \r\n");
          out.write("onmouseout=\"this.style.background='white'; this.style.textDecoration='none';\">소스 보기</a> &nbsp;&nbsp; | &nbsp;&nbsp;\r\n");
          out.write("\r\n");
          out.write("<a id=\"hypertext\" href=\"/Intranet/logout\" onMouseover=\"this.style.background='#96FFFF'; this.style.textDecoration='underline';\" \r\n");
          out.write("onmouseout=\"this.style.background='white'; this.style.textDecoration='none';\">로그아웃</a>&nbsp;&nbsp; ]\r\n");
          out.write(" \r\n");
          out.write(" \r\n");
          out.write("</ul>");
          out.write("\r\n");
          out.write("</div>\r\n");
          out.write("\r\n");
          out.write("<div class=\"registerForm\">\r\n");
          out.write("	<form name=\"registerForm\" method=\"post\" id=\"registerForm\">\r\n");
          out.write("\r\n");
          out.write("         <h1>게시물 등록</h1>\r\n");
          out.write("         <div class=\"nameForm\">\r\n");
          out.write("         	<input type=\"hidden\" name=\"userid\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">\r\n");
          out.write("         	<input type=\"text\" name=\"username\" class=\"username\" value=\"작성자 : ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${username}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("님\" disabled />\r\n");
          out.write("         	<input type=\"hidden\" name=\"writer\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${username}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">\r\n");
          out.write("         </div>\r\n");
          out.write("         <div class=\"titleForm\"><input type=\"text\" name=\"title\" id=\"title\" class=\"title\" placeholder=\"제목을 입력하세요.\"></div>\r\n");
          out.write("         <div class=\"textareaForm\" cols=\"100\" row=\"500\"><textarea id=\"content\" name=\"content\" placeholder=\"여기에 내용을 입력하세요\"></textarea></div>\r\n");
          out.write("	</form> \r\n");
          out.write("         <div class=\"fileuploadForm\">\r\n");
          out.write("         	<input id=\"input_file\" type=\"file\" style=\"display:none;\" multiple />\r\n");
          out.write("  			<div id=\"fileClick\">파일 첨부를 하기 위해서는 클릭하거나 여기로 파일을 드래그 하세요.<br>첨부파일은 최대 5개까지 등록이 가능합니다.</div>\r\n");
          out.write("  			<div id=\"fileUploadList\"></div>\r\n");
          out.write("  		    <div style=\"text-align:center;\">\r\n");
          out.write("  		    	<button class=\"register_btn\" onclick=\"register()\">게시글 등록</button>\r\n");
          out.write("         		 <button class=\"cancel_btn\" onclick=\"history.back()\">취소</button>\r\n");
          out.write("         	</div>\r\n");
          out.write("         </div>\r\n");
          out.write("        \r\n");
          out.write("</div>\r\n");
          out.write("\r\n");
          out.write("\r\n");
          out.write("\r\n");
          out.write("</div>\r\n");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
      // /WEB-INF/views/Intranet/../include/nav_top.jsp(8,1) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${authority_code == '01'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("&nbsp;&nbsp; <a id=\"hypertext\" href=\"/Intranet/mbrInfoList\" onMouseover=\"this.style.background='pink'; this.style.textDecoration='underline';\" \r\n");
          out.write("onmouseout=\"this.style.background='white'; this.style.textDecoration='none';\">사용자정보</a>&nbsp;&nbsp; | &nbsp;&nbsp;\r\n");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f3_reused = false;
    try {
      _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
      // /WEB-INF/views/Intranet/../include/nav_top.jsp(12,0) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${authority_code != '01'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
      if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("&nbsp;&nbsp; <a id=\"hypertext\" href=\"/Intranet/mbrInfoView\" onMouseover=\"this.style.background='pink'; this.style.textDecoration='underline';\" \r\n");
          out.write("onmouseout=\"this.style.background='white'; this.style.textDecoration='none';\">사용자정보</a>&nbsp;&nbsp; | &nbsp;&nbsp;\r\n");
          int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
      _jspx_th_c_005fif_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f3_reused);
    }
    return false;
  }
}
