/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.52
 * Generated at: 2021-11-26 05:37:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/C:/SpringFrameWork_STS/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/board/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1637549191945L));
    _jspx_dependants.put("jar:file:/C:/SpringFrameWork_STS/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/board/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<title>자바 스프링을 이용한 게시판 작성</title>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("function loginCheck(){\r\n");
      out.write("\r\n");
      out.write("	if(document.loginForm.userid.value == '') \r\n");
      out.write("		{\r\n");
      out.write("		alert('아이디를 입력하세요.');\r\n");
      out.write("		document.loginForm.userid.focus();\r\n");
      out.write("		return false;\r\n");
      out.write("		}\r\n");
      out.write("	var Passwd = document.getElementById('userpasswd').value;\r\n");
      out.write("    if(Passwd == '')\r\n");
      out.write("    	{\r\n");
      out.write("    	alert('비밀번호를 입력하세요.');\r\n");
      out.write("    	document.loginForm.userpasswd.focus();\r\n");
      out.write("    	return false;\r\n");
      out.write("    	}\r\n");
      out.write("    document.loginForm.action = '/board/login';\r\n");
      out.write("    document.loginForm.submit();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function press() {\r\n");
      out.write("	\r\n");
      out.write("	if(event.keyCode == 13){ loginCheck(); }\r\n");
      out.write("	\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<style>\r\n");
      out.write("body { font-family: \"나눔고딕\", \"맑은고딕\" }\r\n");
      out.write("h1 { font-family: \"HY견고딕\" }\r\n");
      out.write("a:link { color: black; }\r\n");
      out.write("a:visited { color: black; }\r\n");
      out.write("a:hover { color: blue; }\r\n");
      out.write("a:active { color: red; }\r\n");
      out.write("#hypertext { text-decoration-line: none; cursor: hand; }\r\n");
      out.write("#topBanner {\r\n");
      out.write("       margin-top:10px;\r\n");
      out.write("       margin-bottom:10px;\r\n");
      out.write("       max-width: 500px;\r\n");
      out.write("       height: auto;\r\n");
      out.write("       display: block; margin: 0 auto;\r\n");
      out.write("}\r\n");
      out.write("   \r\n");
      out.write(".loginForm {\r\n");
      out.write("  /* position:absolute; */\r\n");
      out.write("  width:900px;\r\n");
      out.write("  height:auto;\r\n");
      out.write("  padding: 20px, 20px;\r\n");
      out.write("  background-color:#FFFFFF;\r\n");
      out.write("  text-align:center;\r\n");
      out.write("  /* top:50%; \r\n");
      out.write("  left:50%;\r\n");
      out.write("  transform: translate(-50%,-50%);\r\n");
      out.write("  */\r\n");
      out.write("  border:5px solid gray;\r\n");
      out.write("  border-radius: 30px;\r\n");
      out.write("}   \r\n");
      out.write("   \r\n");
      out.write(".idForm{\r\n");
      out.write("  border-bottom: 2px solid #adadad;\r\n");
      out.write("  margin: 30px;\r\n");
      out.write("  padding: 10px 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nameForm{\r\n");
      out.write("  border-bottom: 2px solid #adadad;\r\n");
      out.write("  margin: 30px;\r\n");
      out.write("  padding: 10px 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".titleForm{\r\n");
      out.write("  border-bottom: 2px solid #adadad;\r\n");
      out.write("  margin: 30px;\r\n");
      out.write("  padding: 10px 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".passwdForm{\r\n");
      out.write("  border-bottom: 2px solid #adadad;\r\n");
      out.write("  margin: 30px;\r\n");
      out.write("  padding: 10px 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".userid, .username, .userpasswd {\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  border:none;\r\n");
      out.write("  outline:none;\r\n");
      out.write("  color: #636e72;\r\n");
      out.write("  font-size:16px;\r\n");
      out.write("  height:25px;\r\n");
      out.write("  background: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".bottomText {\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  font-size: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".login_btn  {\r\n");
      out.write("  position:relative;\r\n");
      out.write("  left:40%;\r\n");
      out.write("  transform: translateX(-50%);\r\n");
      out.write("  margin-bottom: 40px;\r\n");
      out.write("  width:80%;\r\n");
      out.write("  height:40px;\r\n");
      out.write("  background: linear-gradient(125deg,#81ecec,#6c5ce7,#81ecec);\r\n");
      out.write("  background-position: left;\r\n");
      out.write("  background-size: 200%;\r\n");
      out.write("  color:white;\r\n");
      out.write("  font-weight: bold;\r\n");
      out.write("  border:none;\r\n");
      out.write("  cursor:pointer;\r\n");
      out.write("  transition: 0.4s;\r\n");
      out.write("  display:inline;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".devInfo {\r\n");
      out.write("  \r\n");
      out.write("  margin-top: 50px;\r\n");
      out.write(" }\r\n");
      out.write("\r\n");
      out.write(".navi_top_tbl {\r\n");
      out.write("	width: 800px;\r\n");
      out.write("	text-align: right;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navi_bottom_tbl {\r\n");
      out.write("	width: 800px;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".InfoTable {\r\n");
      out.write("      border-collapse: collapse;\r\n");
      out.write("      border-top: 3px solid #168;\r\n");
      out.write("      width: 800px;  \r\n");
      out.write("    }  \r\n");
      out.write("    .InfoTable th {\r\n");
      out.write("      color: #168;\r\n");
      out.write("      background: #f0f6f9;\r\n");
      out.write("      text-align: center;\r\n");
      out.write("    }\r\n");
      out.write("    .InfoTable th, .InfoTable td {\r\n");
      out.write("      padding: 10px;\r\n");
      out.write("      border: 1px solid #ddd;\r\n");
      out.write("    }\r\n");
      out.write("    .InfoTable th:first-child, .InfoTable td:first-child {\r\n");
      out.write("      border-left: 0;\r\n");
      out.write("    }\r\n");
      out.write("    .InfoTable th:last-child, .InfoTable td:last-child {\r\n");
      out.write("      border-right: 0;\r\n");
      out.write("    }\r\n");
      out.write("    .InfoTable tr td:first-child{\r\n");
      out.write("      text-align: center;\r\n");
      out.write("    }\r\n");
      out.write("    .InfoTable caption{caption-side: top; }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"home_body_div\" align=center>\r\n");
      out.write("\r\n");
      out.write("	<div>\r\n");
      out.write("		<img id=\"topBanner\" src =\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/logo.jpg\" title=\"서울기술교육센터\" >\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<form name=\"loginForm\" method=\"post\" class=\"loginForm\" onsubmit=\"loginCheck()\">\r\n");
      out.write("     \r\n");
      out.write("     ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("     \r\n");
      out.write("     ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("	</form>\r\n");
      out.write("\r\n");
      out.write("   	<div class=\"devInfo\" align=\"center\">\r\n");
      out.write("   		<table class=\"InfoTable\">\r\n");
      out.write("   			<caption>본 웹사이트는 자바 스프링 프레임워크를 활용한 게시판 작성 예제입니다.</caption>\r\n");
      out.write("   			<tr><th>항목</th><th>내용</th></tr>\r\n");
      out.write("   			<tr><td>현재 시간</td><td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${serverTime}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("   			<tr><td>서버 버전</td><td>");
      out.print(application.getServerInfo() );
      out.write("</td>\r\n");
      out.write("   			<tr><td>자바 버전</td><td>");
      out.print(System.getProperty("java.version") );
      out.write("</td>\r\n");
      out.write("   			<tr><td>서블릿 버전</td><td>");
      out.print( application.getMajorVersion() );
      out.write('.');
      out.print( application.getMinorVersion() );
      out.write("</td>\r\n");
      out.write("   			<tr><td>JSP 버전</td><td>");
      out.print( JspFactory.getDefaultFactory().getEngineInfo().getSpecificationVersion() );
      out.write("</td>\r\n");
      out.write("   			<tr><td>자바 스프링 버전</td><td>");
      out.print(org.springframework.core.SpringVersion.getVersion() );
      out.write("</td>\r\n");
      out.write("   		</table>\r\n");
      out.write("   	</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/home.jsp(183,5) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member == null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("     	<h1>로그인</h1>\r\n");
          out.write("     	<div class=\"loginFormDivision\">\r\n");
          out.write("         	<div class=\"idForm\"><input type=\"text\" name=\"userid\" id=\"userid\" class=\"userid\" placeholder=\"아이디를 입력하세요.\"></div>\r\n");
          out.write("         	<div class=\"passwdForm\"><input type=\"password\" id=\"userpasswd\" name=\"userpasswd\" class=\"userpasswd\" onkeydown=\"press(this.form)\" placeholder=\"비밀번호를 입력하세요.\"></div>\r\n");
          out.write("         	<input type=\"button\" id=\"login_btn\" class=\"login_btn\" value=\"로그인\" onclick=\"loginCheck()\"> \r\n");
          out.write("     	</div> \r\n");
          out.write("     \r\n");
          out.write("     	<div class=\"bottomText\">사용자가 아니면 ▶<a id=\"hypertext\" href=\"/board/mbrInfoRegister\" \r\n");
          out.write("     	       onMouseover=\"this.style.background='pink'; this.style.textDecoration='underline';\" \r\n");
          out.write("     	       onmouseout=\"this.style.background='white'; this.style.textDecoration='none';\">여기</a>를 눌러 등록을 해주세요.<br><br></div>\r\n");
          out.write("     ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/home.jsp(196,5) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${message == false}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("         <p style=\"color:red;\">로그인 에러 !!! 아이디와 패스워드를 확인하세요.</p>\r\n");
          out.write("     ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }
}
